---
# Spotify repo
- name: "Add Spotify repository key"
  apt_key:
    url: "https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg"
    state: present
  become: true

- name: "Add Spotify repository"
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
  become: true

- name: Upgrade all packages to the latest version"
  become: true
  apt:
    name: "*"
    state: latest
    update_cache: yes
  tags: upgrade

- name: "Install tools and stuff"
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    autoclean: yes
    force: yes
  tags: upgrade

- name: Install asdf suff
  include_tasks: asdf.yml
  tags:
    - upgrade
    - asdf

- name: Install NeoVim
  include_tasks: neovim.yml
  tags: neovim

- name: Install Wezterm
  include_tasks: wezterm.yml
  tags: wezterm

- name: Install DBeaver
  include_tasks: dbeaver.yml
  tags: dbeaver

- name: Install Slack
  include_tasks: slack.yml
  tags: slack

- name: Install VSCode
  include_tasks: vscode.yml
  tags: vscode

- name: Install postman
  include_tasks: postman.yml
  tags: postman

- name: Install NVM
  include_tasks: nvm.yml
  tags: nvm

- name: Install Zoom
  include_tasks: zoom.yml
  tags: zoom

- name: Install Chrome
  include_tasks: chrome.yml
  tags: chrome
