---
- name: Clone dotfiles configuration
  become: true
  shell: git clone git@github.com:Leninner/dotfiles.git /home/{{ user }}/dotfiles

- name: "Add configuration files"
  become: true
  shell: ln -s /home/{{ user }}/dotfiles/{{ item }} /home/{{ user }}/{{ item }}
  with_items: [".zshrc", ".p10k.zsh"]
  tags: dotfiles

- name: Source zshrc
  become: true
  shell: source /home/{{ user }}/.zshrc
  tags: dotfiles

# Neovim Config is manage on package part
- name: "Init Neovim repo"
  become: true
  file:
    path: "/home/{{ user }}/.config/nvim/"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: dotfiles

# Wezterm Config is manage on package part
- name: "Init Wezterm repo"
  become: true
  file:
    path: "/home/{{ user }}/.config/wezterm/"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: dotfiles
