---
- name: Clone dotfiles configuration
  become: true
  shell: git clone https://github.com/Leninner/dotfiles.git /home/{{ user }}/dotfiles

- name: "Add configuration files"
  become: true
  shell: ln -s /home/{{ user }}/dotfiles/{{ item }} /home/{{ user }}/{{ item }}
  with_items: [".zshrc", ".p10k.zsh"]
  tags: dotfiles

- name: Source zshrc
  become: true
  shell: source /home/{{ user }}/.zshrc
  tags: dotfiles
