- name: Create main directories
  become: true
  tags: directories
  block:
    - name: Dev
      file:
        path: "/home/{{ user }}/dev"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0755

    - name: Dotfiles
      file:
        path: "/home/{{ user }}/dotfiles"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0755

    - name: Scripts
      file:
        path: "/home/{{ user }}/scripts"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0755

    - name: Projects
      file:
        path: "home/{{ user }}/projects"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0755
