---
- name: "Update Hostname"
  hostname:
    name: "{{ custom_hostname }}"
  become: true

- name: "Set timezone"
  timezone:
    name: "{{ timezone }}"
  become: true

- name: Directories
  include_tasks: directories.yml
  tags: directories

- name: Fonts
  include_tasks: fonts.yml
  tags: fonts

- name: ZSH setup
  include_tasks: zsh-setup.yml
  tags: zsh
