---
- name: Get the current hostname
  command: hostnamectl --static
  register: current_hostname

- name: Set hostname if it is not already set
  become: true
  hostname:
    name: "{{ custom_hostname }}"
  when: current_hostname.stdout != "{{ custom_hostname }}"

- name: "Set timezone"
  timezone:
    name: "{{ timezone }}"
  become: true

- name: Directories
  include_tasks: directories.yml
  tags: directories

- name: Fonts
  include_tasks: fonts.yml
  tags: fonts
