- name: ZSH
  become: true
  tags: zsh
  block:
    - name: Install zsh
      apt: name=zsh

    - name: Change shell to zsh
      shell: chsh -s $(which zsh)

    - name: Check that the oh-my-zsh exists
      stat:
        path: "/home/{{ user }}/.oh-my-zsh"
      register: oh_my_stats

    - name: Oh-My-Zsh
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
      when: oh_my_stats.stat.exists == False
      become_user: "{{ user }}"

    - name: Check that the powerlevel10k exists
      stat:
        path: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k"
      register: powerlevel10k_stats

    - name: Powerlevel10K
      shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
      when: powerlevel10k_stats.stat.exists == False
      become_user: "{{ user }}"
