- name: Install Zsh
  become: true
  block:
    - name: Check if Oh-My-Zsh is installed
      stat:
        path: "/home/{{ user }}/.oh-my-zsh"
      register: oh_my_zsh_installed

    - name: Install Oh-My-Zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "/home/{{ user }}/.oh-my-zsh"
        version: master
      become_user: "{{ user }}"
      when: oh_my_zsh_installed.stat.exists == False

    - name: Check current shell for the user
      command: "getent passwd {{ user }} | awk -F: '{print $7}'"
      register: current_shell

    - name: Ensure default shell is zsh
      shell: chsh -s $(which zsh) "{{ user }}"
      when: current_shell.stdout != "/usr/bin/zsh"

    - name: Check if Powerlevel10K theme is installed
      stat:
        path: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k"
      register: powerlevel10k_installed

    - name: Install Powerlevel10K theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1
      become_user: "{{ user }}"
      when: powerlevel10k_installed.stat.exists == False

    - name: Check if Zsh Autosuggestions is installed
      stat:
        path: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      register: autosuggestions_installed

    - name: Install Zsh Autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        depth: 1
      become_user: "{{ user }}"
      when: autosuggestions_installed.stat.exists == False

    - name: Check if Zsh Syntax Highlighting is installed
      stat:
        path: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      register: syntax_highlighting_installed

    - name: Install Zsh Syntax Highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        depth: 1
      become_user: "{{ user }}"
      when: syntax_highlighting_installed.stat.exists == False

    - name: Check if Fast Syntax Highlighting is installed
      stat:
        path: "/home/{{ user }}/.oh-my-zsh/custom/plugins/fast-syntax-highlighting"
      register: fast_syntax_highlighting_installed

    - name: Install Fast Syntax Highlighting plugin
      git:
        repo: https://github.com/zdharma-continuum/fast-syntax-highlighting.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/fast-syntax-highlighting"
        depth: 1
      become_user: "{{ user }}"
      when: fast_syntax_highlighting_installed.stat.exists == False

    - name: Check if Zsh Autocomplete is installed
      stat:
        path: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autocomplete"
      register: autocomplete_installed

    - name: Install Zsh Autocomplete plugin
      git:
        repo: https://github.com/marlonrichert/zsh-autocomplete.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autocomplete"
        depth: 1
      become_user: "{{ user }}"
      when: autocomplete_installed.stat.exists == False
