---
- name: Gnome installation
  become: true
  tags: gnome
  block:
    - name: "Install tools and stuff"
      become: true
      apt:
        name: "{{ packages }}"
        state: latest
        autoclean: yes

    - name: "Remove tools (not needed, games etc.)"
      become: true
      apt:
        name: "{{ to_remove }}"
        state: absent

    - name: "Copy wallpaper file"
      become: true
      become_user: "{{ user }}"
      copy:
        src: "files/wallpaper.jpg"
        dest: "/home/{{ user }}/.wallpaper.jpg"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Parameter PC by using dconf
      include_tasks: dconf.yml
