---
- name: "Check current theme"
  ansible.builtin.command:
    cmd: dconf read {{ dconf_path_theme }}
  register: dconf_theme_value
  changed_when: false

- name: "Download and set the theme"
  block:
    - name: "Ensure the Github projects directory exists"
      ansible.builtin.file:
        path: "~/projects/github"
        state: directory
        mode: 0755

    - name: "Clone the Marble-shell-theme repository"
      ansible.builtin.git:
        repo: "https://github.com/imarkoff/Marble-shell-theme.git"
        dest: "/home/{{ user }}/projects/github/Marble-shell-theme"
        version: main

    - name: "Run the install script"
      ansible.builtin.command:
        cmd: python3 /home/{{ user }}/projects/github/Marble-shell-theme/install.py -a --filled

    - name: "Set Gnome theme"
      become: true
      become_user: "{{ user }}"
      dconf:
        key: "{{ dconf_path_theme }}"
        value: "'Marble-blue-dark'"
        state: present
  when: dconf_theme_value != 'Marble-blue-dark'
